# Generated by Django 4.1.1 on 2022-09-19 15:14

import ProjApp.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ProjApp", "0002_video_text_image_file_content"),
    ]

    operations = [
        migrations.AlterModelOptions(name="content", options={"ordering": ["order"]},),
        migrations.AlterModelOptions(name="module", options={"ordering": ["order"]},),
        migrations.AddField(
            model_name="content",
            name="order",
            field=ProjApp.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="module",
            name="order",
            field=ProjApp.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="content",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="ProjApp.module",
            ),
        ),
    ]
